dist: xenial

language: node_js
node_js:
  - '10.14.2'

addons:
  chrome: stable

script:
  - npm run build
  # - npm run test

notifications:
  email: false

before_deploy:
  - cd dist
  - echo "$NPMRC_LINE1_REGISTRY" > .npmrc
  - echo "$NPMRC_LINE2_REGISTRY_AUTH" >> .npmrc

deploy:
  provider: npm
  skip_cleanup: true
  email: github@careevolution.com
  api_key: "$PROGET_CAREEV_APIKEY"
  on:
    tags: true
    repo: CareEvolution/ngx-popper
    all_branches: true
